# Generated by Django 5.2.8 on 2026-08-27 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complaints', '0001_initial'),
        ('product_master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('risk_engine', 'Risk Engine Prioritization'), ('complaint', 'Citizen Complaint'), ('ecommerce_flag', 'E-commerce Flagged Listing')], max_length=50)),
                ('priority_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('pending', 'Pending Inspection'), ('in_progress', 'In Progress'), ('done', 'Inspection Done')], db_index=True, default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_inspections', to=settings.AUTH_USER_MODEL)),
                ('complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_targets', to='complaints.complaint')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_targets', to='product_master.product')),
            ],
            options={
                'db_table': 'inspection_targets',
                'ordering': ['-priority_score', '-created_at'],
            },
        ),
    ]
