# Generated by Django 5.2.8 on 2026-08-27 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complaints', '0001_initial'),
        ('product_master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImprovementNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rectification_deadline', models.DateField()),
                ('business_response', models.TextField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('pending', 'Pending Response'), ('rectified', 'Rectified / Compliant'), ('escalated', 'Escalated to Penalty')], default='pending', max_length=30)),
            ],
            options={
                'db_table': 'improvement_notices',
            },
        ),
        migrations.CreateModel(
            name='PenaltyCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid'), ('waived', 'Waived'), ('overdue', 'Overdue')], default='pending', max_length=30)),
                ('appeal_status', models.CharField(choices=[('none', 'No Appeal'), ('filed', 'Appeal Filed'), ('resolved', 'Appeal Resolved')], default='none', max_length=30)),
            ],
            options={
                'db_table': 'penalty_cases',
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(choices=[('first_time', 'First-Time Procedural'), ('repeat', 'Repeat Violation'), ('fraud', 'Fraud / Serious Violation')], default='first_time', max_length=30)),
                ('status', models.CharField(choices=[('open', 'Open'), ('notice_sent', 'Notice Sent'), ('rectification_window', 'Rectification Window Active'), ('verified', 'Rectification Verified'), ('escalated', 'Escalated to Penalty'), ('closed', 'Closed'), ('appealed', 'Appealed')], db_index=True, default='open', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='complaints.complaint')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opened_cases', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='product_master.product')),
            ],
            options={
                'db_table': 'cases',
                'ordering': ['-created_at'],
            },
        ),
    ]
