# Generated by Django 5.2.8 on 2026-08-27 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('compliance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='violation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='compliance.violation'),
        ),
        migrations.AddField(
            model_name='improvementnotice',
            name='case',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='improvement_notice', to='cases.case'),
        ),
        migrations.AddField(
            model_name='improvementnotice',
            name='issued_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_notices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='improvementnotice',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_notices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='penaltycase',
            name='approved_by_controller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_penalties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='penaltycase',
            name='case',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='penalty_case', to='cases.case'),
        ),
        migrations.AddField(
            model_name='penaltycase',
            name='escalated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalated_penalties', to=settings.AUTH_USER_MODEL),
        ),
    ]
