# Generated by Django 5.2.8 on 2026-08-27 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_context', models.CharField(choices=[('citizen', 'Citizen'), ('officer', 'Field Officer')], max_length=30)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('capture_method', models.CharField(choices=[('barcode', 'Barcode Scan'), ('single_image', 'Single Image'), ('guided_capture', 'Guided Multi-Angle Capture'), ('manual_search', 'Manual Search')], default='guided_capture', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('reviewed', 'Reviewed')], default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='product_master.product')),
            ],
            options={
                'db_table': 'scans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(db_index=True, max_length=50)),
                ('extracted_value', models.TextField()),
                ('confidence_score', models.FloatField(default=0.0)),
                ('font_size_mm', models.FloatField(blank=True, null=True)),
                ('placement_zone', models.CharField(blank=True, max_length=100, null=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_fields', to='scans.scan')),
            ],
            options={
                'db_table': 'extracted_fields',
            },
        ),
        migrations.CreateModel(
            name='ScanImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=500)),
                ('angle_type', models.CharField(choices=[('front_panel', 'Front Panel'), ('declaration_panel', 'Declaration Panel'), ('close_up', 'Close-Up'), ('barcode', 'Barcode'), ('wrap_around', 'Wrap Around')], max_length=50)),
                ('quality_check_passed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='scans.scan')),
            ],
            options={
                'db_table': 'scan_images',
                'ordering': ['created_at'],
            },
        ),
    ]
