# Generated by Django 5.2.8 on 2026-08-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='role_context',
            field=models.CharField(choices=[('citizen', 'Citizen'), ('officer', 'Field Officer'), ('field_officer', 'Field Officer')], max_length=30),
        ),
        migrations.AlterField(
            model_name='scanimage',
            name='image_url',
            field=models.TextField(),
        ),
    ]
