# Generated by Django 5.1.15 on 2026-09-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0002_alter_scan_role_context_alter_scanimage_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='canonical_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
