# Generated by Django 5.2.8 on 2026-08-27 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcommerceListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(db_index=True, max_length=100)),
                ('raw_listing_data', models.JSONField(default=dict)),
                ('screening_result', models.CharField(choices=[('compliant', 'Compliant'), ('flagged', 'Flagged for Review'), ('pending', 'Pending Screening')], db_index=True, default='pending', max_length=30)),
                ('flagged_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecommerce_listings', to='product_master.product')),
            ],
            options={
                'db_table': 'ecommerce_listings',
                'ordering': ['-created_at'],
            },
        ),
    ]
