# Generated by Django 5.2.8 on 2026-08-27 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtin_barcode', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('brand_name', models.CharField(db_index=True, max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('food', 'Food & Beverages'), ('electronics', 'Electronics'), ('medical_device', 'Medical Devices'), ('general', 'General Commodities'), ('import', 'Imported Goods')], default='general', max_length=50)),
                ('manufacturer_name', models.CharField(max_length=255)),
                ('manufacturer_address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registered_by_business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'products',
                'ordering': ['-created_at'],
            },
        ),
    ]
