# Generated by Django 5.2.8 on 2026-08-27 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RuleSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_no', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('gazette_url', models.CharField(blank=True, max_length=500, null=True)),
                ('published_date', models.DateField()),
            ],
            options={
                'db_table': 'rule_sources',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id_code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('section_ref', models.CharField(max_length=255)),
                ('category', models.CharField(db_index=True, max_length=50)),
                ('condition', models.JSONField(default=dict)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_force', 'In Force'), ('repealed', 'Repealed')], db_index=True, default='draft', max_length=30)),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='rules_engine.rule')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='rules_engine.rulesource')),
            ],
            options={
                'db_table': 'rules',
                'ordering': ['rule_id_code'],
            },
        ),
    ]
