# Generated by Django 5.2.8 on 2026-08-28 16:37

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules_engine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_no', models.CharField(db_index=True, max_length=100, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('source_text', models.TextField(help_text='Full text of notification or amendment clause')),
                ('gazette_url', models.CharField(blank=True, max_length=500, null=True)),
                ('published_date', models.DateField(default=datetime.date.today)),
                ('date_detected', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(db_index=True, default='general', max_length=50)),
                ('status', models.CharField(choices=[('new', 'New'), ('drafted', 'Drafted'), ('approved', 'Approved'), ('published', 'Published')], db_index=True, default='new', max_length=30)),
            ],
            options={
                'db_table': 'rule_notifications',
                'ordering': ['-date_detected'],
            },
        ),
        migrations.CreateModel(
            name='InspectionWeightConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_engine_weight', models.FloatField(default=0.5)),
                ('complaint_weight', models.FloatField(default=0.3)),
                ('ecommerce_weight', models.FloatField(default=0.2)),
                ('repeat_offense_multiplier', models.FloatField(default=1.5)),
                ('category_multipliers', models.JSONField(default=dict, help_text="Category-specific risk multipliers e.g. {'food': 1.2, 'medical_device': 1.4}")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_inspection_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inspection_weight_configs',
            },
        ),
        migrations.CreateModel(
            name='RuleDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id_code', models.CharField(db_index=True, max_length=100)),
                ('section_ref', models.CharField(max_length=255)),
                ('category', models.CharField(db_index=True, default='general', max_length=50)),
                ('old_clause_text', models.TextField(blank=True, default='', help_text='Current in-force legal clause')),
                ('new_clause_text', models.TextField(help_text='Proposed amendment clause text')),
                ('proposed_condition', models.JSONField(default=dict, help_text='JSON condition schema (required_field, format_check, font_size_check, etc.)')),
                ('effective_date', models.DateField(blank=True, help_text='Planned effective date set upon approval', null=True)),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('revised', 'Revised'), ('approved', 'Approved'), ('published', 'Published')], db_index=True, default='pending_review', max_length=30)),
                ('comments', models.JSONField(default=list, help_text='Audit log of review comments and revision history')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewing_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_rule_drafts', to=settings.AUTH_USER_MODEL)),
                ('supersedes_rule', models.ForeignKey(blank=True, help_text='Existing live rule to be superseded when published', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by_drafts', to='rules_engine.rule')),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts', to='rules_engine.rulenotification')),
            ],
            options={
                'db_table': 'rule_drafts',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='RuleSimulationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_scans_evaluated', models.IntegerField(default=0)),
                ('before_compliance_rate', models.FloatField(default=0.0, help_text='Percentage (0-100)')),
                ('after_compliance_rate', models.FloatField(default=0.0, help_text='Percentage (0-100)')),
                ('projected_violation_diff', models.IntegerField(default=0, help_text='Estimated change in violation count')),
                ('metrics', models.JSONField(default=dict, help_text='Detailed category breakdown and impact analytics')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_results', to='rules_engine.ruledraft')),
            ],
            options={
                'db_table': 'rule_simulation_results',
                'ordering': ['-created_at'],
            },
        ),
    ]
