# Generated by Django 5.2.8 on 2026-08-27 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('product_master', '0001_initial'),
        ('rules_engine', '0001_initial'),
        ('scans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(choices=[('compliant', 'Compliant'), ('non_compliant', 'Non-Compliant'), ('needs_review', 'Needs Review')], max_length=30)),
                ('overall_confidence', models.FloatField(default=0.0)),
                ('evaluated_against_rule_set_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_compliance_checks', to=settings.AUTH_USER_MODEL)),
                ('scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_check', to='scans.scan')),
            ],
            options={
                'db_table': 'compliance_checks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compliance_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='compliance.compliancecheck')),
                ('evidence_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violations', to='scans.scanimage')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='rules_engine.rule')),
            ],
            options={
                'db_table': 'violations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductComplianceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_first_time', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_history_entries', to='cases.case')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_history', to='product_master.product')),
                ('violation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries', to='compliance.violation')),
            ],
            options={
                'db_table': 'product_compliance_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
