# Generated by Django 5.1.15 on 2026-09-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancecheck',
            name='report_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
